version: '3.2'
services:
  nginx:
    build:
      context: "nginx"
    network_mode: "host"
    volumes:
      - ../logs:/var/log/nginx
  dns:
    build:
      context: "./dns"
    ports:
      - "5443:5443"
